/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import com.mysql.jdbc.PreparedStatement;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Array;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.function.Function;
import static javafx.scene.input.KeyCode.R;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static jdk.nashorn.internal.codegen.CompilerConstants.className;

/**
 *
 * @author Hansi
 */
public class InfoAge extends javax.swing.JFrame implements ActionListener {

    ArrayList<AgeInfo> list1 = new ArrayList<AgeInfo>();
    ArrayList<AgeInfo> list2 = new ArrayList<AgeInfo>();
    ArrayList<AgeInfo> list3 = new ArrayList<AgeInfo>();
    ArrayList<AgeInfo> list4 = new ArrayList<AgeInfo>();
    ArrayList<AgeInfo> list5 = new ArrayList<AgeInfo>();
    ArrayList<AgeInfo> list6 = new ArrayList<AgeInfo>();
    ArrayList<AgeInfo> list7 = new ArrayList<AgeInfo>();
    ArrayList<AgeInfo> list8 = new ArrayList<AgeInfo>();
    ArrayList<AgeInfo> list9 = new ArrayList<AgeInfo>();
    
    DBShow db = new DBShow();
    ArrayList<File2nd> flist;
    ArrayList<File2nd> Flist2;

    /**
     * Creates new form InfoAge
     */
    public InfoAge() {
        initComponents();
    }

    void load2months() {
        list1 = db.getDetails1();
        Months2 m1 = new Months2(list1);
        tblfull.setModel(m1);
    }
    
     void load4months() {
        list2 = db.getDetails2();
        Months4 m2 = new Months4(list2);
        tblfull.setModel(m2);
    }

    void load6months() {
        list3 = db.getDetails3();
        Months6 m3 = new Months6(list3);
        tblfull.setModel(m3);

    }

    void load9months() {
        list4 = db.getDetails4();;
        Months9 m4 = new Months9(list4);

        tblfull.setModel(m4);
    }

    void load1yr() {
        list5 = db.getDetails5();;
        Year1 y1 = new Year1(list5);
        tblfull.setModel(y1);
    }

    void load18months() {
        list6 = db.getDetails6();;
        Months18 m4 = new Months18(list6);
        tblfull.setModel(m4);
    }

    void load3yr() {
        list7 = db.getDetails7();;
        Year3 y2 = new Year3(list7);
        tblfull.setModel(y2);
    }

    void load5yr() {
        list8 = db.getDetails8();;
        Year5 y3 = new Year5(list8);
        tblfull.setModel(y3);
    }

    void load12yr() {
        list9 = db.getDetails9();;
        Year12 y4 = new Year12(list9);
        tblfull.setModel(y4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfull = new javax.swing.JTable();
        btnmonth2 = new javax.swing.JButton();
        btnmonth6 = new javax.swing.JButton();
        btnmonth9 = new javax.swing.JButton();
        btnyear1 = new javax.swing.JButton();
        btnmonths18 = new javax.swing.JButton();
        btnyear3 = new javax.swing.JButton();
        btnyear5 = new javax.swing.JButton();
        btnyear12 = new javax.swing.JButton();
        btnmonth4 = new javax.swing.JButton();

        jCheckBox3.setText("jCheckBox3");

        jCheckBox2.setText("jCheckBox2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        tblfull.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblfull.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblfull.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblfull);

        btnmonth2.setText("2 months");
        btnmonth2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmonth2ActionPerformed(evt);
            }
        });

        btnmonth6.setText("6 months");
        btnmonth6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmonth6ActionPerformed(evt);
            }
        });

        btnmonth9.setText("9 months");
        btnmonth9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmonth9ActionPerformed(evt);
            }
        });

        btnyear1.setText("1 years");
        btnyear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyear1ActionPerformed(evt);
            }
        });

        btnmonths18.setText("18 months");
        btnmonths18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmonths18ActionPerformed(evt);
            }
        });

        btnyear3.setText("3 years");
        btnyear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyear3ActionPerformed(evt);
            }
        });

        btnyear5.setText("5 years");
        btnyear5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyear5ActionPerformed(evt);
            }
        });

        btnyear12.setText("12 years");
        btnyear12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyear12ActionPerformed(evt);
            }
        });

        btnmonth4.setText("4 months");
        btnmonth4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmonth4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnmonth2)
                .addGap(18, 18, 18)
                .addComponent(btnmonth4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmonth6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmonth9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnyear1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmonths18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnyear3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnyear5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnyear12)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmonth2)
                    .addComponent(btnmonth6)
                    .addComponent(btnmonth9)
                    .addComponent(btnyear1)
                    .addComponent(btnmonths18)
                    .addComponent(btnyear3)
                    .addComponent(btnyear5)
                    .addComponent(btnyear12)
                    .addComponent(btnmonth4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmonth2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmonth2ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
        String namem = (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
        System.out.println(namem);

        File2nd b = new File2nd();
        b.setBabyname(nameb);
         b.setIdnum(namem);
        b.setAge(age);
        b.setMonth2sms("sent");
        Dbfile2 ddb = new Dbfile2();
        Details bc = new Details();
        bc.setBabyname(nameb);
        bc.setIdNum(namem);
        bc.setMonth2sms("sent");
        DbOperationage d=new DbOperationage();
        d.update1(bc);
        System.out.println("details update wenawa");
        if (ddb.update1(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }


    }//GEN-LAST:event_btnmonth2ActionPerformed

    private void btnmonth6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmonth6ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
         String namem = (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
        

        File2nd b = new File2nd();
        b.setBabyname(nameb);
         b.setIdnum(namem);
        b.setMonth6sms("sent");
        Dbfile2 ddb = new Dbfile2();
         Details bc = new Details();
        bc.setBabyname(nameb);
        bc.setIdNum(namem);
        
        bc.setMonth6sms("sent");
        DbOperationage d=new DbOperationage();
        d.update3(bc);
         if (ddb.update3(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }
    }//GEN-LAST:event_btnmonth6ActionPerformed

    private void btnmonth9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmonth9ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
        String namem = (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
        

        File2nd b = new File2nd();
        b.setBabyname(nameb);
        b.setIdnum(namem);
        b.setAge(age);
        b.setMonth9sms("sent");
        Dbfile2 ddb = new Dbfile2();
         Details bc = new Details();
        bc.setBabyname(nameb);
         bc.setIdNum(namem);
        bc.setMonth9sms("sent");
        DbOperationage d=new DbOperationage();
        d.update4(bc);
        if (ddb.update4(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }
    }//GEN-LAST:event_btnmonth9ActionPerformed

    private void btnyear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyear1ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
        String namem = (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
      

        File2nd b = new File2nd();
        b.setBabyname(nameb);
         b.setIdnum(namem);
        b.setAge(age);
        b.setYear1sms("sent");
        Dbfile2 ddb = new Dbfile2();
         Details bc = new Details();
        bc.setIdNum(namem);
        bc.setYear1sms("sent");
        DbOperationage d=new DbOperationage();
        d.update5(bc);
         if (ddb.update5(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }
    }//GEN-LAST:event_btnyear1ActionPerformed

    private void btnmonths18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmonths18ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
        String namem = (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
        

        File2nd b = new File2nd();
        b.setBabyname(nameb);
         b.setIdnum(namem);
        b.setAge(age);
        b.setMonth18sms("sent");
        Dbfile2 ddb = new Dbfile2();
         Details bc = new Details();
        bc.setBabyname(nameb);
         bc.setIdNum(namem);
        bc.setMonth18sms("sent");
        DbOperationage d=new DbOperationage();
        d.update6(bc);
         if (ddb.update6(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }
    }//GEN-LAST:event_btnmonths18ActionPerformed

    private void btnyear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyear3ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
        String namem = (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
        

        File2nd b = new File2nd();
        b.setBabyname(nameb);
        b.setIdnum(namem);
        b.setAge(age);
        b.setYear3sms("sent");
        Dbfile2 ddb = new Dbfile2();
         Details bc = new Details();
        bc.setBabyname(nameb);
         bc.setIdNum(namem);
        bc.setYear3sms("sent");
        DbOperationage d=new DbOperationage();
        d.update7(bc);
        if (ddb.update7(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }
    }//GEN-LAST:event_btnyear3ActionPerformed

    private void btnyear5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyear5ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
        String namem = (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
        

        File2nd b = new File2nd();
        b.setBabyname(nameb);
         b.setIdnum(namem);
        b.setAge(age);
        b.setYear5sms("sent");
        Dbfile2 ddb = new Dbfile2();
         Details bc = new Details();
        bc.setBabyname(nameb);
         bc.setIdNum(namem);
        bc.setYear5sms("sent");
        DbOperationage d=new DbOperationage();
        d.update8(bc);
         if (ddb.update8(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }
    }//GEN-LAST:event_btnyear5ActionPerformed

    private void btnyear12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyear12ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
        String namem = (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
        

        File2nd b = new File2nd();
        b.setBabyname(nameb);
         b.setIdnum(namem);
        b.setAge(age);
        b.setYear12sms("sent");
        Dbfile2 ddb = new Dbfile2();
         Details bc = new Details();
        bc.setBabyname(nameb);
         bc.setIdNum(namem);
        bc.setYear12sms("sent");
        DbOperationage d=new DbOperationage();
        d.update9(bc);
        if (ddb.update9(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }
       
    }//GEN-LAST:event_btnyear12ActionPerformed

    private void btnmonth4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmonth4ActionPerformed
        int row = tblfull.getSelectedRow();

        String nameb = (String) tblfull.getValueAt(row, 0);
        String namem= (String) tblfull.getValueAt(row, 1);
        String age = (String) tblfull.getValueAt(row, 3);
       System.out.println("balanna");
        System.out.println(namem);

        File2nd b = new File2nd();
        b.setBabyname(nameb);
       
        b.setIdnum(namem);
        b.setAge(age);
        b.setMonth4sms("sent");
        Dbfile2 ddb = new Dbfile2();
         Details bc = new Details();
        bc.setBabyname(nameb);
        bc.setIdNum(namem);
        bc.setMonth4sms("sent");
        DbOperationage d=new DbOperationage();
        d.update2(bc);
        if (ddb.update2(b)) {
            tblfull.setSelectionBackground(Color.YELLOW);
            
        } else {
            tblfull.setSelectionBackground(Color.RED);
            
        }
    }//GEN-LAST:event_btnmonth4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoAge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoAge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoAge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoAge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoAge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmonth2;
    private javax.swing.JButton btnmonth4;
    private javax.swing.JButton btnmonth6;
    private javax.swing.JButton btnmonth9;
    private javax.swing.JButton btnmonths18;
    private javax.swing.JButton btnyear1;
    private javax.swing.JButton btnyear12;
    private javax.swing.JButton btnyear3;
    private javax.swing.JButton btnyear5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblfull;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println("meka wada");//To change body of generated methods, choose Tools | Templates.
    }
}
